export enum AccountType {
  WALLET_MAIN = 'WALLET_MAIN',
  AGENT = 'AGENT',
  WALLET_ESCROW = 'WALLET_ESCROW',
  TREASURY = 'TREASURY',
  FEES = 'FEES',
  RESERVE = 'RESERVE',
  SAVINGS = 'SAVINGS'
}
